services:
    crisistextline.user_profile_manager:
        class: CrisisTextLine\UserProfileBundle\Service\UserProfileManager
        arguments:
            - "@doctrine.orm.entity_manager"
    crisistextline.create_profile_on_login:
        class: CrisisTextLine\UserProfileBundle\EventListener\InteractiveLoginListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@crisistextline.user_profile_manager"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: createProfileOnLogin, priority: -9999999 }