<?php

namespace CrisisTextLine\UserProfileBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileFieldRepository extends EntityRepository
{
}
