<?php

namespace CrisisTextLine\UserProfileBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends EntityRepository
{

    public function findByUserId($uid)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.user = :uid')
            ->setParameter('uid', $uid)
        ;

        try {
            return $qb->getQuery()->getSingleResult();
        } catch (\Exception $e) {
            return false;
        }

    }

}
