<?php

namespace CrisisTextLine\UserProfileBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends EntityRepository
{
}
